# Bun configuration for CLI-Kit

# JSX/TSX/TUIX configuration
[jsx]
factory = "jsx"
fragment = "Fragment"
importSource = "."

[test]
# Preload setup files (uncomment when setup.ts is created)
# preload = ["./src/testing/setup.ts"]

# Enable coverage reporting
coverage = true
coverageDirectory = "./coverage"
coverageReporter = ["text", "lcov"]

# Set test timeout (in milliseconds)
timeout = 5000

# Test file patterns
root = "./"

# Exclude node_modules and other directories from testing
ignore = ["node_modules/**", "dist/**", ".git/**"]

# Exclude files from coverage
coverageSkipTestFiles = true

# File extension mappings for .tuix files
[loader]
".tuix" = "tsx"